version: "3.9"

services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    container_name: nginx
    depends_on:
      - frontend
      - backend
    networks:
      - my-jotts

  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - my-jotts

  backend:
    restart: always
    build:
      context: ./portal-backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: production
    ports:
      - "4000:4000"
    env_file:
      - ./portal-backend/.env
    networks:
      - my-jotts

  postgres:
    image: postgres:15
    container_name: portal_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - ./portal-backend/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my-jotts

volumes:
  pgdata: {}

networks:
  my-jotts:
    driver: bridge
