apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: activity-steps-skaffold
build:
  local:
    push: false
  artifacts:
    - image: bizzhle/strapi-backend
      context: strapi-backend
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - ./k8s/ingress.yaml
    - ./k8s/strapi-deployment.yaml
