apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgdb-persistent-volume
spec:
  capacity:
    storage: 5Gi
  storageClassName: activity-local-storage
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  # Specify the path to persistent the volumes
  hostPath:
    path: "/var/lib/strapi/storage"
