apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdb-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: activity-local-storage
