version: '3.5'

services:
  backend:
    container_name: portal-backend
    image: portal-backend
    build: .
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://admin:admin@db:5432/activity-steps-db
    ports:
      - '4000:4000'
    depends_on:
      - db
    # networks:
    #   - activity-moves

  db:
    container_name: portal_dbmodel
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - db_data:/data/postgres
    environment:
      - POSTGRES_DB=activity-steps-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/data/postgres

volumes:
  db_data: {}

networks:
  activity-moves:
    driver: bridge
    name: activity-moves
