version: '3'

includes:
  db: sql/Taskfile.yml

tasks:
  build:
    cmds:
      - npm ci
      - npm run build

  start:
    desc: Runs the environmemt locally
    cmds:
      - npm ci
      - npm start

  start-dev:
    desc: Runs the environmemt locally
    cmds:
      - npm run start:dev

  docker:build:
    desc: Builds docker container
    cmds:
      - docker compose -p portal-backend build

  docker:clean:
    desc: Clean docker container
    cmds:
      - docker rm -f $(docker ps -a -q)

  docker:debug:
    desc: Runs the application in dev-debug mode from previously build docker images
    cmds:
      - docker compose -p portal-backend -f docker-compose.yml -f docker-compose.debug.yml up

  docker:debugd:
    desc: Runs the application in dev-debug mode from previously build docker images, detached
    cmds:
      - docker compose -p portal-backend -f docker-compose.yml -f docker-compose.debug.yml up -d

  docker:servicesd:
    desc: starts all docker containers as background services to enable local dev
    cmds:
      - docker-compose -p portal-backend up -d db

  docker:services:
    desc: starts all docker containers as background services to enable local dev
    cmds:
      - docker-compose -p portal-backend up db
