name: Block Direct Push to Main

on:
  push:
    branches:
      - main

jobs:
  block-push:
    runs-on: ubuntu-latest
    steps:
      - name: Fail Direct Push
        run: |
          echo "Direct pushes to the main branch are not allowed. Please use a pull request."
          exit 1
